### ISSUE TITLE
ER diagram

### ISSUE THREAD

**Issue by jaanos** [damjanm/Glasbene-lestvice#1]
Kot sta bila opozorjena že na zagovoru, naj izpeljanih atributov ne bo na ER diagramu (kasneje lahko sicer naredita poglede z želenimi izpeljanimi atributi). Seveda naj bosta leto izdaje pesmi ter uvrstitev na lestvici atributa, ne entiteti.

Iz ER diagrama tudi ni jasno, kako so organizirani glasbeniki - če sta hotela narediti dedovanje, bi morala narediti glavno entiteto, iz nje trikotnik, pod njim pa podentitete. Glede na to, da je med avtorji in izvajalci prekrivanje, svetujem, da imate eno samo entiteto za glasbenike, potem pa dve relaciji med glasbeniki in pesmimi - eno za avtorstvo, drugo pa za izvajanje.

Namesto dvojnih črt imata v ER diagramu lahko tudi debele črte - na vajah smo risali dvojne črte samo zato, ker bi na tablo težje risali debele črte. Če sta imela težave z dvojnimi puščicami, imata tako lahko namesto njih debele puščice.

**Comment by ghost** [comment]
Pozdravljeni!

Hvala za popravke. Zanima naju, če lahko to popraviva po torku, ker sva do takrat zasedena.

Lepo vas pozdravljam,
Just Bajželj

**Comment by jaanos** [comment]
Ni problema - popravita, ko bosta imela čas.

**Comment by damjanm** [comment]
Zdaj sem popravil ER diagram, mislim, da je tako kot ste svetovali? [32b0ef7](https://github.com/damjanm/Glasbene-lestvice/commit/019b240d4541f7e50f450bf186c4adca93d2ab4f)

**Comment by jaanos** [comment]
Sedaj izgleda v redu. Odvisno od podatkov, ki jih imata, bi morda predlagal še, da imate svojo entiteto za albume, saj imajo ti lahko še vrsto svojih atributov.
