### ISSUE TITLE
Uvoz več stolpcev

### ISSUE THREAD

**Issue by damjanm** [damjanm/Glasbene-lestvice#2]
Živjo,

zanima me, kako naj uvozimo stoplce X.1st.week - X.91st.week razpredelnice billboard. A damo kar vse stolpce v bazi, ali jih grupiramo v enem vektorju in tega vektorja dodamo v razpredelnici kot nov stolpec? 

Zaenkrat je tako narejeno, da uvozi samo prvi stolpec.

Lp,
Damjan

**Comment by jaanos** [comment]
Podatke iz teh stolpcev grupirajta v eni razpredelnici, ki jo bosta potem uvozila kot tabelo v bazi z referenco na vrstice (preostanka) razpredelnice `billboard`. Grupiranje lahko izvedeta npr. tako:

``` R
library(reshape2)
library(dplyr)
ranks <- data.frame(id = 1:nrow(billboard), billboard[35:125]) %>%
  melt("id", variable.name = "week", value.name = "rank")
ranks$week <- as.numeric(ranks$week)
```

Tukaj je za referenco uporabljena kar zaporedna številka vrstice v razpredelnici `billboard` - to bo seveda potrebno dodati pri uvozu preostanka razpredelnice; lahko pa za to poskrbi stolpec tipa `SERIAL`, a bosta potem morala te ID-je potegniti nazaj iz baze po uvozu.

Če imata težave s knjižnico dplyr, si namestita zadnjo verzijo R (več detajlov najdeta pri BraMira/Mirjam-Spela#2).

**Comment by jaanos** [comment]
Še to: svetujem, da si v RStudiu naredita projekt - kliknita desno zgoraj, kjer piše _Project: (None)_, ter izberite _New Project..._ in _Existing Directory_, nato pa izberite mapo, kjer se nahaja vajin projekt. Nastala bo datoteka s končnico `.Rproj`, ki jo dodajta v repozitorij - z git bosta lahko tako delala tudi neposredno v RStudiu (desno zgoraj se bo pojavil zavihek _Git_).

**Comment by damjanm** [comment]
Super, hvala za opombe, mislim da sem jih pravilno upošteval. Midva sva do zdaj uporabljala Github Desktop, ampak ta način je boljši.
