### ISSUE TITLE
Težave s shiny aplikacijo

### ISSUE THREAD

**Issue by ghost** [damjanm/Glasbene-lestvice#3]
Pozdravljeni!

S shinyjem probavam narediti aplikacij, ki bi glede na izbrani datum vrnila podatke o pesmih ki so se na izbran dan pojavile na lestvici, vendar mi vrača error messeage : "character string is not in a standard unambiguous format". Če pa datum vstavim ročno, mi vse normalno deluje.

Lepo vas pozdravljam,
Just Bajželj

**Comment by jaanos** [comment]
Najprej bi svetoval, da Shiny aplikacijo razbijeta na dve datoteki `server.R` in `ui.R`. V prvi kličete funkcijo `shinyServer`, ki kot argument dobi funkcijo, ki jo trenutno dasta v spremenljivko `server`; v drugi pa funkcijo `shinyUI`, ki kot argument dobi klic funkcije `fluidPage`, ki ga trenutno dasta v `ui`. Tako bo namesto gumba _Source_ gumb _Run App_, ki požene aplikacijo (klic `shinyApp` tako ni potreben). V `server.R` potem poskrbite za povezavo z bazo. Lahko si pogledata pri sošolcih, kako imajo narejeno.

Če hočeta dostopati do vrednosti v vnosnih poljih, uporabite polja objekta `input`, npr.

``` R
  output$hist<-renderTable({
    filter(billboard,Date.Entered==as.Date(input$date))
  })
```

**Comment by ghost** [comment]
Pozdravljeni!

Vse sem popravil, sedaj stvar deluje.

Hvala za pomoč

**Comment by jaanos** [comment]
Še to bi vaju opozoril: uporabniku _javnost_ dajta pravico dostopa do baze (poglejta si na spletni učilnici), potem pa v Shiny aplikaciji namesto `auth.R` vključita npr. datoteko `auth_public.R` s podatki za povezavo z uporabnikom _javnost_. Tako bo možna takojšnja uporaba aplikacije po kloniranju repozitorija.
